"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// const { hello } = require('@crispy/test');
const test_1 = require("@crispy/test");
// import {alpha} from '@crispy/test/alpha';
const alpha_1 = require("@crispy/test/alpha");
const items_1 = require("@crispy/test/alpha/items");
console.log((0, test_1.hello)('crispy'), '\n\n');
(0, test_1.testAlpha)();
console.log('\n\n');
console.log(test_1.alpha.items.item1());
console.log(test_1.alpha.items.item2());
console.log(test_1.alpha.items.item3());
console.log('\n\n');
console.log(alpha_1.items.item1());
console.log(alpha_1.items.item2());
console.log(alpha_1.items.item3());
console.log('\n\n');
console.log(alpha_1.items);
console.log('\n\n');
console.log((0, items_1.item1)());
console.log((0, items_1.item2)());
console.log((0, items_1.item3)());
console.log('\n\n');
